services:
  - type: web
    name: dota2-guide
    runtime: python
    repo: https://github.com/TippiestLand/dota2-guide
    plan: free
    region: frankfurt
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn api_server:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dota2-guide-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: tippi
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: dota2-guide-db
    databaseName: dota2_guide
    plan: free